# Test REST API calls here.
# OPTIONS http://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=b1d3b456717c4a2e921dd4cb0379e828  

# GET http://newsapi.org/v2/top-headlines?sources=billboard&apiKey=b1d3b456717c4a2e921dd4cb0379e828

# OPTIONS https://spotifystefan-skliarovv1.p.rapidapi.com/addTracksToPlaylist

# OPTIONS https://api.twitter.com/1.1/statuses/home_timeline.json

# // TODO: RESTful API
# // TODO: Resolve CORS and do I have to pay for the news service or can it be free?

# GET http://newsapi.org/v2/everything?domains=billboard.com&apiKey=b1d3b456717c4a2e921dd4cb0379e828


GET https://gnews.io/api/v3/search?q=music&source=billboard&token=f4f33a3a088407a836e3a419ae99c96f 

